# Generated by assume-cloaker scripts/release.sh. Edit packaging/homebrew/assume-cloaker.rb instead.
cask "assume-cloaker" do
  version "0.1.0"
  sha256 "0f27292912535afd475874e4b87589dee48155d5d8953220d0cc51e6a98f5f9f"

  url "https://github.com/gtalmor/assume-cloaker/releases/download/v#{version}/AssumeCloaker-#{version}.zip"
  name "Assume Cloaker"
  desc "Menu bar app that keeps Keycloak (saml2aws) and AWS SSO sessions alive"
  homepage "https://github.com/gtalmor/assume-cloaker"

  depends_on macos: :sequoia
  # The CLIs the app drives; Homebrew installs them alongside.
  depends_on formula: ["awscli", "saml2aws", "kubernetes-cli"]

  app "Assume Cloaker.app"

  postflight_steps do
    # Ad-hoc signed, not notarized: drop the download quarantine so it opens.
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/Assume Cloaker.app"]
  end

  uninstall quit: "com.gtalmor.AssumeCloaker"

  zap trash: [
    "~/.config/assume-cloaker",
    "~/Library/Logs/AssumeCloaker",
    "~/Library/Preferences/com.gtalmor.AssumeCloaker.plist",
  ]
end
