# Generated by assume-keycloaker scripts/release.sh. Edit packaging/homebrew/assume-keycloaker.rb instead.
# uploads the zip as a release of the (public) tap repo. The code repo is private.
cask "assume-keycloaker" do
  version "0.4.1"
  sha256 "01ebf99ca90533996fd51a76a01ecba2d96102f17a76c671506bae2771ca019c"

  url "https://github.com/gtalmor/homebrew-tap/releases/download/assume-keycloaker-v#{version}/AssumeKeycloaker-#{version}.zip"
  name "Assume Keycloaker"
  desc "Menu bar app that keeps your work sessions signed in"
  homepage "https://github.com/gtalmor/homebrew-tap"

  depends_on macos: :sequoia

  app "Assume Keycloaker.app"

  postflight_steps do
    # Ad-hoc signed, not notarized: drop the download quarantine so it opens.
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/Assume Keycloaker.app"]
  end

  uninstall quit: "com.gtalmor.AssumeKeycloaker"

  zap trash: [
    "~/.config/assume-cloaker",
    "~/Library/Logs/AssumeCloaker",
    "~/Library/Preferences/com.gtalmor.AssumeCloaker.plist",
    "~/.config/assume-keycloaker",
    "~/Library/Logs/AssumeKeycloaker",
    "~/Library/Preferences/com.gtalmor.AssumeKeycloaker.plist",
  ]
end
